name: Keep Supabase Alive
on:
    schedule:
      - cron: '0 0 */3 * *'
    workflow_dispatch:   # 支持手动触发

  jobs:
    ping:
      runs-on: ubuntu-latest
      steps:
        - name: Ping Supabase
          run: |
            curl -sf "https://xgjojrmmfijpfukuigdu.supabase.co/rest/v1/gpus?select=id&limit=1" \
              -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnam9qcm1tZmlqcGZ1a3VpZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3Nzk0NzMsImV4cCI6MjA5NTM1NTQ3M30.M7_sZpnY77lZrmlvaOFwwrnbFtZLg1wO9E-iI5W1jg0"
            curl -sf "https://xgjojrmmfijpfukuigdu.supabase.co/auth/v1/health" \
              -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnam9qcm1tZmlqcGZ1a3VpZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3Nzk0NzMsImV4cCI6MjA5NTM1NTQ3M30.M7_sZpnY77lZrmlvaOFwwrnbFtZLg1wO9E-iI5W1jg0"
